### ISSUE TITLE
Should be able to bring up additional bees

### ISSUE THREAD

**Issue by xiongchiamiov** [newsapps/beeswithmachineguns#76]
After running into limits of the current number of machines, it's helpful to increase to more.  I would expect `bees up` to do this, either by adding the number I specify with `-n` or using that as a total amount.

To get around this, we reverse-engineered the format a little and moved `~/.bees`, launched more machines, then copied the entries from the old file into the new one.  This works, although you have to be careful to not include a newline character at the bottom of the file, which vim does by default.

**Comment by FliesLikeABrick** [comment]
@xiongchiamiov  I have a patch coming that fixes this.  The current codebase does have code that tries to add additional bees, however it has 2 bugs that break it due to mishandling of how existing instances (versus reservations) are counted.  I should have a fix pushed and PR open by the end of the day today or tomorrow.

**Comment by FliesLikeABrick** [comment]
PR #193 opened and linked, this should fix the issue with additional bees.

**Comment by FliesLikeABrick** [comment]
@xiongchiamiov  or @cosmin  this issue should be able to be closed now that #193  was merged
