### ISSUE TITLE
Bees do not complete the mission

### ISSUE THREAD

**Issue by JulianGindi** [newsapps/beeswithmachineguns#91]
I had two bees active and neither of them 'made it to the action'. This seems to be a pretty consistent problem on my end, any ideas on what could be going on?

**Comment by JulianGindi** [comment]
Bumping this again. Still getting the error. Have 4 bees, making 10000 requests 250 at a time. None completed their mission. Any ideas?

**Comment by tbergeron** [comment]
I think this is because of the image it used to spawn bees: https://dragkh.wordpress.com/2012/07/08/bees-with-machine-guns-and-ec2-at-aws/

Seems it's now missing the httpd-tools package. I think we can connect to our bees manually and install it like that: yum install httpd-tools -y

But I'm not able to connect to my bees at the moment even with opened 22 port so I'm still stuck.

**Comment by JulianGindi** [comment]
Let me try using a custom AMI and see how that works. Will submit a PR if I get things working.

**Comment by tbergeron** [comment]
That's what I'd love to be able to do but I don't know how to use custom AMI with bees. Thanks and good luck!

**Comment by JulianGindi** [comment]
Looks like there is a hard-coded AMI [here](https://github.com/newsapps/beeswithmachineguns/blob/5ff4c620b1e64590d3aee7ebd14d4c30ee11c253/beeswithmachineguns/main.py#L68) I'll try changing that to include all the packages we might need. I'll probably add a flag to specify a custom AMI when you launch the bees as well.
